include ../config.inc
CBMC ?= ../..

SRC = logo.cpp html_escape.cpp syntax_highlighting.cpp

include $(CBMC)/src/config.inc
include $(CBMC)/src/common

INCLUDES= -I $(CBMC)/src

CLEANFILES = 

all: $(OBJ)

###############################################################################

