include ../config.inc
CBMC ?= ../..

SRC = solver.cpp predicate.cpp fixed_point.cpp

include $(CBMC)/src/config.inc
include $(CBMC)/src/common

INCLUDES= -I $(CBMC)/src

CLEANFILES = 

all: $(OBJ)

###############################################################################

