include ../config.inc
CBMC ?= ../..

SRC = concrete_transformers.cpp  interval_map.cpp  interval_map_domain.cpp\
      interval_widening.cpp

include $(CBMC)/src/config.inc
include $(CBMC)/src/common

INCLUDES= -I $(CBMC)/src

CLEANFILES = 

all: $(OBJ)

###############################################################################

