include ../config.inc
CBMC ?= ../..

SRC = function_ssa.cpp ssa_domain.cpp guard_domain.cpp

include $(CBMC)/src/config.inc
include $(CBMC)/src/common

INCLUDES= -I $(CBMC)/src

CLEANFILES = 

all: $(OBJ)

###############################################################################

