/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "files/just_assert.c"
int main(void) 
{ 

  {
#line 4
  if (0) {
    ERROR: 
#line 5
    assert(0);
  } else {

  }
#line 7
  return (0);
}
}
