include ../config.inc
CBMC ?= ../..

SRC = call_graph.cpp summary.cpp index.cpp get_function.cpp path_utils.cpp

include $(CBMC)/src/config.inc
include $(CBMC)/src/common

INCLUDES= -I $(CBMC)/src

CLEANFILES = 

all: $(OBJ)

###############################################################################

